// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate
// For now, we define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Enum types matching our database schema
export type CoverageStatus =
  | "incomplete"
  | "pending_verification"
  | "verified"
  | "inactive";

export type ChargeSetStatus = "draft" | "coder_review" | "finalized" | "void";

export type ClaimStatus =
  | "ready"
  | "submitted"
  | "ack_accepted"
  | "ack_rejected"
  | "adjudicated"
  | "closed";

export type EnrollmentStatus =
  | "draft"
  | "stedi_action_required"
  | "provider_action_required"
  | "provisioning"
  | "live"
  | "rejected"
  | "canceled";

export type LedgerEntryType =
  | "charge"
  | "patient_payment"
  | "insurance_payment"
  | "adjustment"
  | "refund"
  | "writeoff";

export type WorkItemType =
  | "coverage_incomplete"
  | "eligibility_failed"
  | "charge_review"
  | "claim_rejected"
  | "remit_unmatched"
  | "denial_review";

export type WorkItemStatus =
  | "pending"
  | "assigned"
  | "in_progress"
  | "completed"
  | "escalated";

export type Database = {
  public: {
    Tables: {
      patients: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          middle_name: string | null;
          dob: string;
          sex: string;
          ssn_last_four: string | null;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          zip_code: string;
          phone: string | null;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          middle_name?: string | null;
          dob: string;
          sex: string;
          ssn_last_four?: string | null;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          zip_code: string;
          phone?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          middle_name?: string | null;
          dob?: string;
          sex?: string;
          ssn_last_four?: string | null;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          zip_code?: string;
          phone?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      guarantors: {
        Row: {
          id: string;
          patient_id: string;
          relationship: string;
          first_name: string;
          last_name: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          zip_code: string;
          phone: string | null;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          relationship: string;
          first_name: string;
          last_name: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          zip_code: string;
          phone?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          relationship?: string;
          first_name?: string;
          last_name?: string;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          zip_code?: string;
          phone?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payers: {
        Row: {
          id: string;
          stedi_payer_id: string;
          name: string;
          payer_type: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          stedi_payer_id: string;
          name: string;
          payer_type: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          stedi_payer_id?: string;
          name?: string;
          payer_type?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      coverage_policies: {
        Row: {
          id: string;
          patient_id: string;
          payer_id: string;
          plan_type: string | null;
          group_number: string | null;
          member_id: string;
          subscriber_id: string | null;
          priority: number;
          effective_from: string;
          effective_to: string | null;
          status: CoverageStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          payer_id: string;
          plan_type?: string | null;
          group_number?: string | null;
          member_id: string;
          subscriber_id?: string | null;
          priority?: number;
          effective_from: string;
          effective_to?: string | null;
          status?: CoverageStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          payer_id?: string;
          plan_type?: string | null;
          group_number?: string | null;
          member_id?: string;
          subscriber_id?: string | null;
          priority?: number;
          effective_from?: string;
          effective_to?: string | null;
          status?: CoverageStatus;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscribers: {
        Row: {
          id: string;
          coverage_id: string;
          member_id: string;
          group_number: string | null;
          first_name: string;
          last_name: string;
          dob: string;
          relationship_to_patient: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          coverage_id: string;
          member_id: string;
          group_number?: string | null;
          first_name: string;
          last_name: string;
          dob: string;
          relationship_to_patient: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          coverage_id?: string;
          member_id?: string;
          group_number?: string | null;
          first_name?: string;
          last_name?: string;
          dob?: string;
          relationship_to_patient?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      eligibility_checks: {
        Row: {
          id: string;
          coverage_id: string;
          provider_id: string;
          date_of_service: string;
          request_payload: Json;
          response_payload: Json | null;
          is_active: boolean | null;
          network_status: string | null;
          copay_amount: number | null;
          deductible_remaining: number | null;
          oop_max_remaining: number | null;
          benefits_summary: Json | null;
          checked_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          coverage_id: string;
          provider_id: string;
          date_of_service: string;
          request_payload: Json;
          response_payload?: Json | null;
          is_active?: boolean | null;
          network_status?: string | null;
          copay_amount?: number | null;
          deductible_remaining?: number | null;
          oop_max_remaining?: number | null;
          benefits_summary?: Json | null;
          checked_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          coverage_id?: string;
          provider_id?: string;
          date_of_service?: string;
          request_payload?: Json;
          response_payload?: Json | null;
          is_active?: boolean | null;
          network_status?: string | null;
          copay_amount?: number | null;
          deductible_remaining?: number | null;
          oop_max_remaining?: number | null;
          benefits_summary?: Json | null;
          checked_at?: string;
          created_at?: string;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          tax_id: string | null;
          npi: string | null;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          zip_code: string;
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          tax_id?: string | null;
          npi?: string | null;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          zip_code: string;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          tax_id?: string | null;
          npi?: string | null;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          zip_code?: string;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      providers: {
        Row: {
          id: string;
          organization_id: string;
          npi: string;
          first_name: string;
          last_name: string;
          credentials: string | null;
          taxonomy_code: string | null;
          is_billing_provider: boolean;
          is_rendering_provider: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          npi: string;
          first_name: string;
          last_name: string;
          credentials?: string | null;
          taxonomy_code?: string | null;
          is_billing_provider?: boolean;
          is_rendering_provider?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          npi?: string;
          first_name?: string;
          last_name?: string;
          credentials?: string | null;
          taxonomy_code?: string | null;
          is_billing_provider?: boolean;
          is_rendering_provider?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      locations: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          zip_code: string;
          place_of_service_code: string;
          is_primary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          zip_code: string;
          place_of_service_code: string;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          zip_code?: string;
          place_of_service_code?: string;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      encounters: {
        Row: {
          id: string;
          patient_id: string;
          coverage_id: string | null;
          provider_id: string;
          location_id: string;
          start_time: string;
          end_time: string | null;
          place_of_service: string;
          chief_complaint: string | null;
          assessment: string | null;
          plan: string | null;
          notes: string | null;
          is_self_pay: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          coverage_id?: string | null;
          provider_id: string;
          location_id: string;
          start_time: string;
          end_time?: string | null;
          place_of_service: string;
          chief_complaint?: string | null;
          assessment?: string | null;
          plan?: string | null;
          notes?: string | null;
          is_self_pay?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          coverage_id?: string | null;
          provider_id?: string;
          location_id?: string;
          start_time?: string;
          end_time?: string | null;
          place_of_service?: string;
          chief_complaint?: string | null;
          assessment?: string | null;
          plan?: string | null;
          notes?: string | null;
          is_self_pay?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      charge_sets: {
        Row: {
          id: string;
          encounter_id: string;
          version: number;
          status: ChargeSetStatus;
          ai_confidence: number | null;
          ai_rationale: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          finalized_at: string | null;
          voided_at: string | null;
          void_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          encounter_id: string;
          version?: number;
          status?: ChargeSetStatus;
          ai_confidence?: number | null;
          ai_rationale?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          finalized_at?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          encounter_id?: string;
          version?: number;
          status?: ChargeSetStatus;
          ai_confidence?: number | null;
          ai_rationale?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          finalized_at?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      service_lines: {
        Row: {
          id: string;
          charge_set_id: string;
          line_number: number;
          cpt_code: string;
          modifiers: string[];
          dx_codes: string[];
          units: number;
          charge_amount: number;
          dos_from: string;
          dos_to: string;
          place_of_service: string;
          provider_control_number: string;
          ai_suggested: boolean;
          ai_confidence: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          charge_set_id: string;
          line_number: number;
          cpt_code: string;
          modifiers?: string[];
          dx_codes?: string[];
          units?: number;
          charge_amount: number;
          dos_from: string;
          dos_to: string;
          place_of_service: string;
          provider_control_number?: string;
          ai_suggested?: boolean;
          ai_confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          charge_set_id?: string;
          line_number?: number;
          cpt_code?: string;
          modifiers?: string[];
          dx_codes?: string[];
          units?: number;
          charge_amount?: number;
          dos_from?: string;
          dos_to?: string;
          place_of_service?: string;
          provider_control_number?: string;
          ai_suggested?: boolean;
          ai_confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      claims: {
        Row: {
          id: string;
          encounter_id: string;
          charge_set_id: string;
          patient_control_number: string;
          claim_version: number;
          parent_claim_id: string | null;
          status: ClaimStatus;
          total_charge_amount: number;
          stedi_transaction_id: string | null;
          stedi_correlation_id: string | null;
          submitted_at: string | null;
          acknowledged_at: string | null;
          adjudicated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          encounter_id: string;
          charge_set_id: string;
          patient_control_number?: string;
          claim_version?: number;
          parent_claim_id?: string | null;
          status?: ClaimStatus;
          total_charge_amount: number;
          stedi_transaction_id?: string | null;
          stedi_correlation_id?: string | null;
          submitted_at?: string | null;
          acknowledged_at?: string | null;
          adjudicated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          encounter_id?: string;
          charge_set_id?: string;
          patient_control_number?: string;
          claim_version?: number;
          parent_claim_id?: string | null;
          status?: ClaimStatus;
          total_charge_amount?: number;
          stedi_transaction_id?: string | null;
          stedi_correlation_id?: string | null;
          submitted_at?: string | null;
          acknowledged_at?: string | null;
          adjudicated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      claim_responses: {
        Row: {
          id: string;
          claim_id: string;
          response_type: string;
          stedi_transaction_id: string;
          raw_payload: Json;
          parsed_data: Json | null;
          status_code: string | null;
          status_description: string | null;
          processed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          claim_id: string;
          response_type: string;
          stedi_transaction_id: string;
          raw_payload: Json;
          parsed_data?: Json | null;
          status_code?: string | null;
          status_description?: string | null;
          processed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          claim_id?: string;
          response_type?: string;
          stedi_transaction_id?: string;
          raw_payload?: Json;
          parsed_data?: Json | null;
          status_code?: string | null;
          status_description?: string | null;
          processed_at?: string;
          created_at?: string;
        };
      };
      ledger_entries: {
        Row: {
          id: string;
          patient_id: string;
          encounter_id: string | null;
          service_line_id: string | null;
          claim_id: string | null;
          claim_response_id: string | null;
          entry_type: LedgerEntryType;
          amount: number;
          description: string | null;
          carc_code: string | null;
          rarc_code: string | null;
          adjustment_group: string | null;
          reference_number: string | null;
          voided_at: string | null;
          void_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          encounter_id?: string | null;
          service_line_id?: string | null;
          claim_id?: string | null;
          claim_response_id?: string | null;
          entry_type: LedgerEntryType;
          amount: number;
          description?: string | null;
          carc_code?: string | null;
          rarc_code?: string | null;
          adjustment_group?: string | null;
          reference_number?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          encounter_id?: string | null;
          service_line_id?: string | null;
          claim_id?: string | null;
          claim_response_id?: string | null;
          entry_type?: LedgerEntryType;
          amount?: number;
          description?: string | null;
          carc_code?: string | null;
          rarc_code?: string | null;
          adjustment_group?: string | null;
          reference_number?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          created_at?: string;
        };
      };
      work_items: {
        Row: {
          id: string;
          item_type: WorkItemType;
          status: WorkItemStatus;
          priority: number;
          title: string;
          description: string | null;
          patient_id: string | null;
          encounter_id: string | null;
          claim_id: string | null;
          coverage_id: string | null;
          assigned_to: string | null;
          assigned_at: string | null;
          due_at: string | null;
          completed_at: string | null;
          resolution_notes: string | null;
          context: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          item_type: WorkItemType;
          status?: WorkItemStatus;
          priority?: number;
          title: string;
          description?: string | null;
          patient_id?: string | null;
          encounter_id?: string | null;
          claim_id?: string | null;
          coverage_id?: string | null;
          assigned_to?: string | null;
          assigned_at?: string | null;
          due_at?: string | null;
          completed_at?: string | null;
          resolution_notes?: string | null;
          context?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          item_type?: WorkItemType;
          status?: WorkItemStatus;
          priority?: number;
          title?: string;
          description?: string | null;
          patient_id?: string | null;
          encounter_id?: string | null;
          claim_id?: string | null;
          coverage_id?: string | null;
          assigned_to?: string | null;
          assigned_at?: string | null;
          due_at?: string | null;
          completed_at?: string | null;
          resolution_notes?: string | null;
          context?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      processed_stedi_events: {
        Row: {
          id: string;
          transaction_id: string;
          event_type: string;
          processed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          transaction_id: string;
          event_type: string;
          processed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          transaction_id?: string;
          event_type?: string;
          processed_at?: string;
          created_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          table_name: string;
          record_id: string;
          action: string;
          old_data: Json | null;
          new_data: Json | null;
          user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          table_name: string;
          record_id: string;
          action: string;
          old_data?: Json | null;
          new_data?: Json | null;
          user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          table_name?: string;
          record_id?: string;
          action?: string;
          old_data?: Json | null;
          new_data?: Json | null;
          user_id?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      patient_balances: {
        Row: {
          patient_id: string;
          total_charges: number;
          insurance_payments: number;
          patient_payments: number;
          adjustments: number;
          patient_balance: number;
          insurance_balance: number;
        };
      };
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      coverage_status: CoverageStatus;
      charge_set_status: ChargeSetStatus;
      claim_status: ClaimStatus;
      enrollment_status: EnrollmentStatus;
      ledger_entry_type: LedgerEntryType;
      work_item_type: WorkItemType;
      work_item_status: WorkItemStatus;
    };
  };
};
